spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: api-server
server:
  port: 8081
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html
