spring:
  profiles:
    active: local #default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common
    application:
      name: notification

server:
  port: 8084
  servlet:
    context-path: /api
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: jigsee
    password: jigseeadmin!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
---
apis:
  api-base-url: "http://k10s105.p.ssafy.io/api/v1"
