spring:
  application:
    name: common
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_jigsee?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: jigsee
    password: jigsee
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: jig
      username: jigsee
      password: jigseeadmin!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
       format_sql: true
---
#spring:
#  cloud:
#    openfeign:
#      okhttp:
#        enabled: true
---
server:
  port: 8088
---
url:
  api-server: "http://localhost:8080"
---
page-size: 5