name: jigsee
description: SDI JIG Life Cycle Management Project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  freezed: ^2.5.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  shared_preferences: ^2.0.20
  flutter_scalable_ocr: ^2.0.0
  google_ml_kit: ^0.14.0
  image_picker: ^1.1.0
  camera: ^0.10.5+9
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  # assets 경로 지정
  assets:
    - assets/
