name: jigsee
description: SDI JIG Life Cycle Management Project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  freezed: ^2.5.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # assets 경로 지정
  assets:
    - assets/
