spring:
  profiles:
    active: local #default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common
    application:
      name: member

server:
  port: 8082
  servlet:
    context-path: /api

---

spring:
  config:
    activate:
      on-profile: local
  #DB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      url: ${REDIS_URL}

---

spring:
  config:
    activate:
      on-profile: test
  #DB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${TEST_MYSQL_DB_URL}
    username: ${TEST_MYSQL_DB_USERNAME}
    password: ${TEST_MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      url: ${TEST_REDIS_URL}
