spring:
  application:
    name: notification-api
---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: jig
      username: jigsee
      password: jigseeadmin!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
       format_sql: true
---
#spring:
#  cloud:
#    openfeign:
#      okhttp:
#        enabled: true
---
server:
  port: 8088
  servlet:
    context-path: /api
---
apis:
  api-base-url: "http://localhost:8080/api/v1"
